spring:
    application:
        name: TIFW
    ai:
        ollama:
            base-url: http://example.com:11434 # 示例地址
            chat:
                model: deepseek-r1:1.5b
                options:
                    temperature: 0.8
                    top-p: 0.9
                    top-k: 1
        memory:
            redis:
                host: localhost
                port: 6379
                password: example-redis-password # 示例 Redis 密码
                timeout: 5000
        vectorstore:
            milvus:
                client:
                    host: example-host # default: localhost
                    port: 19530 # default: 19530
                    username: root # default: root
                    password: example-milvus-password # 示例 Milvus 密码
                databaseName: default # default: default
                collectionName: vector_store # default: vector_store
                embeddingDimension: 1536 # default: 1536
                indexType: IVF_FLAT # default: IVF_FLAT
                metricType: COSINE # default: COSINE
    datasource:
        driverClassName: com.mysql.cj.jdbc.Driver
        password: example-db-password # 示例数据库密码
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://localhost:3307/tifw?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
        username: root
    servlet:
        multipart:
            max-file-size: 10MB
            max-request-size: 10MB
    thymeleaf:
        cache: false
    codec:
        max-in-memory-size: 50MB
server:
    port: 8083
 
